### ISSUE TITLE
Bug $Db->update() method

### ISSUE THREAD

**Issue by gilbertdim** [requtize/query-builder#4]
I encounter an error while using the `update()` function.

When you execute
```
$DB->table('table')->where('id', 1)->getQuery('update', [ 'name' => 'table_name' ]);
```
The function will return 
```
UPDATE `table` SET `name` = name WHERE `id` = 'table_name'
```

That will throw an error;

Fatal error: Uncaught Error: Wrong parameters for Requtize\QueryBuilder\Exception\QueryExecutionFailException([string $message [, long $code [, Throwable $previous = NULL]]]) in /media/sf_htdocs/candyfactory/vendor/requtize/query-builder/src/QueryBuilder/QueryBuilder/QueryBuilder.php:815 Stack trace: #0 /media/sf_htdocs/candyfactory/vendor/requtize/query-builder/src/QueryBuilder/QueryBuilder/QueryBuilder.php(815): Exception->__construct() #1 /media/sf_htdocs/candyfactory/vendor/requtize/query-builder/src/QueryBuilder/QueryBuilder/QueryBuilder.php(462): Requtize\QueryBuilder\QueryBuilder\QueryBuilder->prepareAndExecute() #2 /media/sf_htdocs/candyfactory/src/register/index.php(27): Requtize\QueryBuilder\QueryBuilder\QueryBuilder->update() #3 {main} thrown in /media/sf_htdocs/candyfactory/vendor/requtize/query-builder/src/QueryBuilder/QueryBuilder/QueryBuilder.php on line 815

**Comment by TheSin-** [comment]
```
diff --git a/includes/QueryBuilder/QueryBuilder/Compiler.php b/includes/QueryBuilder/QueryBuilder/Compiler.php
index e6d2352..e555fe9 100644
--- a/includes/QueryBuilder/QueryBuilder/Compiler.php
+++ b/includes/QueryBuilder/QueryBuilder/Compiler.php
@@ -375,7 +375,7 @@ class Compiler
             }
             else
             {
-                $segment .= $this->quoteColumnName($key).' = '.$key.' , ';
+                $segment .= $this->quoteColumnName($key).' = ?, ';
                 $bindings[] = $value;
             }
         }
```
